name: testing

on:
  push:
    branches:
      - 'main'

jobs:
  transaction:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@master

    - name: setup php
      uses: shivammathur/setup-php@master
      with:
        php-version: 8.3
        coverage: none

    - name: composer install
      run: composer install

    - name: editorconfig-checker
      run: vendor/bin/ec -verbose

    - name: phpstan
      run: vendor/bin/phpstan analyze -c phpstan.neon

    - name: phpunit
      run: vendor/bin/phpunit
